#!/bin/bash
# =============================================================================
# token-tracking.sh — Track token usage per work item across sessions
# =============================================================================
#
# PURPOSE
#   Measures how many API tokens a work item consumes by recording transcript
#   line offsets at start/stop boundaries and summing the token usage fields
#   from assistant turns in the Claude Code session JSONL transcript.
#
#   Designed for beads (`bd`) IDs but accepts any string identifier — works with
#   `none` tracker too. All it needs is a unique ID and the transcript path.
#
# HOW IT WORKS
#   Claude Code writes one JSON object per line to a session transcript file.
#   Each assistant turn includes a .message.usage block with token counts:
#     - input_tokens:                  new (uncached) input tokens
#     - cache_read_input_tokens:       tokens served from prompt cache
#     - cache_creation_input_tokens:   tokens written into prompt cache
#     - output_tokens:                 tokens generated by the model
#
#   This script tracks a line-number "bookmark" in the transcript. On start it
#   records the current line count; on stop it sums all assistant-turn usage
#   between the bookmark and the current end of file.
#
# CROSS-SESSION / COMPACT SUPPORT
#   If a work item spans multiple sessions or a context compaction occurs,
#   use "continue" to bank the tokens accumulated so far and set a new bookmark
#   in the (potentially different) transcript file. Accumulated totals persist
#   across any number of continue calls.
#
# STORAGE
#   Active tracking:   ~/.claude/.token_tracking/<work-id>      (shell-sourceable)
#   Completed items:   ~/.claude/.token_tracking/<work-id>.done (with final totals)
#
# DEPENDENCIES
#   - jq (JSON processing)
#   - sed, wc (line slicing)
#
# USAGE
#   token-tracking.sh start    <work-id> <transcript-path>
#   token-tracking.sh continue <work-id> <transcript-path>
#   token-tracking.sh stop     <work-id> <transcript-path> [--json]
#   token-tracking.sh status   <work-id> <transcript-path> [--json]
#   token-tracking.sh list
#
# EXAMPLES
#   # Start tracking before working on an item
#   .claude/hooks/token-tracking.sh start issue-42 ~/.claude/projects/.../session.jsonl
#
#   # Check progress mid-work
#   .claude/hooks/token-tracking.sh status issue-42 ~/.claude/projects/.../session.jsonl
#
#   # Context compacted or new session — bank and continue
#   .claude/hooks/token-tracking.sh continue issue-42 ~/.claude/projects/.../new-session.jsonl
#
#   # Done — get final report as JSON
#   .claude/hooks/token-tracking.sh stop issue-42 ~/.claude/projects/.../session.jsonl --json
#
#   # See all tracked items
#   .claude/hooks/token-tracking.sh list
#
# OUTPUT (text mode)
#   === Token Usage: issue-42 ===
#     input_tokens:          1,234
#     cache_read_tokens:     456,789
#     cache_creation_tokens: 12,345
#     output_tokens:         4,321
#     turns:                 28
#     total_input:           470,368
#
# OUTPUT (JSON mode)
#   {"work_id":"issue-42","input_tokens":1234,"cache_read_tokens":456789,
#    "cache_create_tokens":12345,"output_tokens":4321,"turns":28}
#
# =============================================================================
set -uo pipefail

TRACK_DIR="$HOME/.claude/.token_tracking"
mkdir -p "$TRACK_DIR"

ACTION="${1:-}"
WORK_ID="${2:-}"
TRANSCRIPT="${3:-}"

# Detect --json flag from any argument position
JSON_OUTPUT=false
for arg in "$@"; do [ "$arg" = "--json" ] && JSON_OUTPUT=true; done

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------

# Sum token usage from assistant turns between two line numbers in a transcript.
sum_tokens() {
    local file="$1"
    local start_line="$2"
    local end_line="$3"

    sed -n "${start_line},${end_line}p" "$file" | jq -c '
        select(.type == "assistant" and .message.usage != null)
        | .message.usage
    ' 2>/dev/null | jq -s '{
        input_tokens: (map(.input_tokens // 0) | add // 0),
        cache_read_input_tokens: (map(.cache_read_input_tokens // 0) | add // 0),
        cache_creation_input_tokens: (map(.cache_creation_input_tokens // 0) | add // 0),
        output_tokens: (map(.output_tokens // 0) | add // 0),
        turns: length
    }'
}

get_line_count() {
    wc -l < "$1"
}

bank_segment() {
    local segment_json="$1"
    accumulated_input=$((accumulated_input + $(echo "$segment_json" | jq '.input_tokens')))
    accumulated_cache_read=$((accumulated_cache_read + $(echo "$segment_json" | jq '.cache_read_input_tokens')))
    accumulated_cache_create=$((accumulated_cache_create + $(echo "$segment_json" | jq '.cache_creation_input_tokens')))
    accumulated_output=$((accumulated_output + $(echo "$segment_json" | jq '.output_tokens')))
    accumulated_turns=$((accumulated_turns + $(echo "$segment_json" | jq '.turns')))
}

write_state() {
    cat > "$1" << EOF
transcript=$2
segments=$3
accumulated_input=$accumulated_input
accumulated_cache_read=$accumulated_cache_read
accumulated_cache_create=$accumulated_cache_create
accumulated_output=$accumulated_output
accumulated_turns=$accumulated_turns
EOF
}

print_report() {
    local label="$1" inp="$2" cr="$3" cc="$4" out="$5" turns="$6"
    echo "=== $label ==="
    echo "  input_tokens:          $inp"
    echo "  cache_read_tokens:     $cr"
    echo "  cache_creation_tokens: $cc"
    echo "  output_tokens:         $out"
    echo "  turns:                 $turns"
    echo "  total_input:           $((inp + cr + cc))"
}

print_json_report() {
    local id="$1" inp="$2" cr="$3" cc="$4" out="$5" turns="$6"
    jq -n \
        --arg id "$id" \
        --argjson input "$inp" \
        --argjson cache_read "$cr" \
        --argjson cache_create "$cc" \
        --argjson output "$out" \
        --argjson turns "$turns" \
        '{work_id:$id, input_tokens:$input, cache_read_tokens:$cache_read,
          cache_create_tokens:$cache_create, output_tokens:$output, turns:$turns}'
}

# -----------------------------------------------------------------------------
# Commands
# -----------------------------------------------------------------------------

case "$ACTION" in
    start)
        [ -z "$WORK_ID" ] || [ -z "$TRANSCRIPT" ] && { echo "Usage: $0 start <work-id> <transcript-path>"; exit 1; }
        TRACK_FILE="$TRACK_DIR/$WORK_ID"

        if [ -f "$TRACK_FILE" ]; then
            echo "Warning: $WORK_ID already has tracking data. Use 'continue' to resume or 'stop' to finalize."
            exit 1
        fi

        CURRENT_LINE=$(get_line_count "$TRANSCRIPT")
        accumulated_input=0 accumulated_cache_read=0 accumulated_cache_create=0
        accumulated_output=0 accumulated_turns=0
        write_state "$TRACK_FILE" "$TRANSCRIPT" "$CURRENT_LINE"
        echo "Started tracking $WORK_ID at line $CURRENT_LINE"
        ;;

    continue)
        [ -z "$WORK_ID" ] || [ -z "$TRANSCRIPT" ] && { echo "Usage: $0 continue <work-id> <transcript-path>"; exit 1; }
        TRACK_FILE="$TRACK_DIR/$WORK_ID"

        if [ ! -f "$TRACK_FILE" ]; then
            echo "Error: No tracking data for $WORK_ID. Use 'start' first."
            exit 1
        fi

        source "$TRACK_FILE"
        LAST_SEGMENT="${segments##*,}"
        OLD_TRANSCRIPT="$transcript"

        if [ -f "$OLD_TRANSCRIPT" ]; then
            OLD_END=$(get_line_count "$OLD_TRANSCRIPT")
            if [ "$LAST_SEGMENT" -lt "$OLD_END" ]; then
                bank_segment "$(sum_tokens "$OLD_TRANSCRIPT" "$((LAST_SEGMENT + 1))" "$OLD_END")"
            fi
        fi

        NEW_LINE=$(get_line_count "$TRANSCRIPT")
        write_state "$TRACK_FILE" "$TRANSCRIPT" "$NEW_LINE"
        echo "Continued tracking $WORK_ID — banked previous segment, new start at line $NEW_LINE"
        ;;

    stop)
        [ -z "$WORK_ID" ] || [ -z "$TRANSCRIPT" ] && { echo "Usage: $0 stop <work-id> <transcript-path> [--json]"; exit 1; }
        TRACK_FILE="$TRACK_DIR/$WORK_ID"

        if [ ! -f "$TRACK_FILE" ]; then
            echo "Error: No tracking data for $WORK_ID. Use 'start' first."
            exit 1
        fi

        source "$TRACK_FILE"
        LAST_SEGMENT="${segments##*,}"
        CURRENT_LINE=$(get_line_count "$TRANSCRIPT")

        if [ "$LAST_SEGMENT" -lt "$CURRENT_LINE" ]; then
            bank_segment "$(sum_tokens "$TRANSCRIPT" "$((LAST_SEGMENT + 1))" "$CURRENT_LINE")"
        fi

        if [ "$JSON_OUTPUT" = true ]; then
            print_json_report "$WORK_ID" \
                "$accumulated_input" "$accumulated_cache_read" "$accumulated_cache_create" \
                "$accumulated_output" "$accumulated_turns"
        else
            print_report "Token Usage: $WORK_ID" \
                "$accumulated_input" "$accumulated_cache_read" "$accumulated_cache_create" \
                "$accumulated_output" "$accumulated_turns"
        fi

        mv "$TRACK_FILE" "$TRACK_FILE.done"
        cat >> "$TRACK_FILE.done" << EOF
final_input=$accumulated_input
final_cache_read=$accumulated_cache_read
final_cache_create=$accumulated_cache_create
final_output=$accumulated_output
final_turns=$accumulated_turns
completed=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
EOF
        if [ "$JSON_OUTPUT" != true ]; then
            echo "  (archived to $TRACK_FILE.done)"
        fi
        ;;

    status)
        [ -z "$WORK_ID" ] || [ -z "$TRANSCRIPT" ] && { echo "Usage: $0 status <work-id> <transcript-path> [--json]"; exit 1; }
        TRACK_FILE="$TRACK_DIR/$WORK_ID"

        if [ ! -f "$TRACK_FILE" ]; then
            echo "Error: No tracking data for $WORK_ID."
            exit 1
        fi

        source "$TRACK_FILE"
        LAST_SEGMENT="${segments##*,}"
        CURRENT_LINE=$(get_line_count "$TRANSCRIPT")

        curr_input=$accumulated_input
        curr_cache_read=$accumulated_cache_read
        curr_cache_create=$accumulated_cache_create
        curr_output=$accumulated_output
        curr_turns=$accumulated_turns

        if [ "$LAST_SEGMENT" -lt "$CURRENT_LINE" ]; then
            SEGMENT_TOKENS=$(sum_tokens "$TRANSCRIPT" "$((LAST_SEGMENT + 1))" "$CURRENT_LINE")
            curr_input=$((curr_input + $(echo "$SEGMENT_TOKENS" | jq '.input_tokens')))
            curr_cache_read=$((curr_cache_read + $(echo "$SEGMENT_TOKENS" | jq '.cache_read_input_tokens')))
            curr_cache_create=$((curr_cache_create + $(echo "$SEGMENT_TOKENS" | jq '.cache_creation_input_tokens')))
            curr_output=$((curr_output + $(echo "$SEGMENT_TOKENS" | jq '.output_tokens')))
            curr_turns=$((curr_turns + $(echo "$SEGMENT_TOKENS" | jq '.turns')))
        fi

        if [ "$JSON_OUTPUT" = true ]; then
            print_json_report "$WORK_ID" \
                "$curr_input" "$curr_cache_read" "$curr_cache_create" \
                "$curr_output" "$curr_turns"
        else
            print_report "In-Progress: $WORK_ID" \
                "$curr_input" "$curr_cache_read" "$curr_cache_create" \
                "$curr_output" "$curr_turns"
        fi
        ;;

    list)
        echo "=== Active Token Tracking ==="
        found=0
        for f in "$TRACK_DIR"/*; do
            [ -f "$f" ] || continue
            case "$f" in *.done) continue ;; esac
            item=$(basename "$f")
            echo "  $item (in progress)"
            found=1
        done
        for f in "$TRACK_DIR"/*.done; do
            [ -f "$f" ] || continue
            item=$(basename "$f" .done)
            (source "$f"; echo "  $item (completed: input=$final_input output=$final_output turns=$final_turns)")
            found=1
        done
        [ "$found" -eq 0 ] && echo "  (none)" || true
        ;;

    *)
        cat << 'HELP'
token-tracking.sh — Track token usage per work item across Claude Code sessions

Commands:
  start    <work-id> <transcript>             Begin tracking at current transcript line
  continue <work-id> <transcript>             Bank previous segment, resume in new transcript
  stop     <work-id> <transcript> [--json]    Finalize, print report, archive as .done
  status   <work-id> <transcript> [--json]    Print running totals without stopping
  list                                        Show all active and completed items

The <work-id> can be anything unique: a bead ID or manual label.
The <transcript> is the session JSONL path (injected by session-start.sh).

Typical workflow:
  1. token-tracking.sh start issue-42 /path/to/session.jsonl
  2. ... work on the item ...
  3. token-tracking.sh status issue-42 /path/to/session.jsonl   # optional check
  4. ... context compacts or new session ...
  5. token-tracking.sh continue issue-42 /path/to/new-session.jsonl
  6. ... finish the item ...
  7. token-tracking.sh stop issue-42 /path/to/session.jsonl --json

Storage:
  Active:    ~/.claude/.token_tracking/<work-id>
  Completed: ~/.claude/.token_tracking/<work-id>.done
HELP
        exit 1
        ;;
esac
